apiVersion: apps/v1
kind: Deployment
metadata:
  name: xyz-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xyzapp
  template:
    metadata:
      labels:
        app: xyzapp
    spec:
      containers:
      - name: xyzapp
        image: nadil95/xyzrepo:latest   # Will be replaced by Jenkins
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: xyz-service
spec:
  type: NodePort
  selector:
    app: xyzapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080   # NodePort to access on browser
