---
- hosts: docker_hosts
  become: yes
  vars:
    image_name: "nadil95/xyztechnologies"   # Docker Hub repo
    container_name: "abcapp"
    host_port: 8081                          # change if 8080 is in use
    container_port: 8080
    build_number: "{{ build_number }}"       # pass from Jenkins

  tasks:
    - name: Stop existing container if running
      docker_container:
        name: "{{ container_name }}"
        state: absent
      ignore_errors: yes
    
    - name: Pull Docker image from Docker Hub
      docker_image:
        name: "{{ image_name }}:{{ build_number }}"
        source: pull
    
    - name: Run Docker container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}:{{ build_number }}"
        ports:
          - "{{ host_port }}:{{ container_port }}"
        state: started
        restart_policy: always
