---
- name: Deploy app container
  hosts: docker
  become: true
  collections:
    - community.docker
  vars:
    app_name: "{{ image_name }}"
    docker_user: "{{ docker_user }}"
    image_tag: "{{ build_number }}"
    image: "{{ docker_user }}/{{ app_name }}:{{ image_tag }}"
    host_port: 8081
    container_port: 8080

  tasks:
    - name: Ensure old container is absent
      community.docker.docker_container:
        name: "{{ app_name }}"
        state: absent
        force_kill: true

    - name: Run new container
      community.docker.docker_container:
        name: "{{ app_name }}"
        image: "{{ image }}"
        published_ports:
          - "{{ host_port }}:{{ container_port }}"
        restart_policy: unless-stopped
